# Dockerfile.dev
FROM node:latest

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json /usr/src/app
RUN npm install

# Copy the entire project
COPY . /usr/src/app

# Expose the port for the Node.js app
EXPOSE 3000

# Run the application in development mode
CMD ["npm", "run", "dev"]
