services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - live-selling-network

  live-selling:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: live-selling
    working_dir: /usr/src/app
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=3000
      - NODE_ENV=${NODE_ENV}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - live-selling-network

networks:
  live-selling-network:
    driver: bridge
